### Tools
[tools]
# install forge cli tool
"github:donaldgifford/forge" = "latest"

# repo tools
markdownlint-cli2 = "0.18.1"
yamlfmt = "0.20.0"
yamllint = "1.37.1"
yq = "4.48.1"
prettier = "3.7.4"

# shell
shellcheck = "latest"
shfmt = "latest"

### Languages

# go
go = "1.25.7"

# rust
rust = "1.92"
